version: '3'
services:
  video_server:
    build:
      context: .
      dockerfile: docker/docker_video_server/Dockerfile
    ports:
      - 5000:5000
    environment:
      - RMQ_HOST=rabbitmq
      - OUT_VIDEO_FOLDER=/src/generations
      - S3_BUCKET_URL=virtual-streamer-output
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
      - VIDEO_FOLDER=/videos
    networks:
      - obs
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - $HOME/.aws/config:/root/.aws/config
      - video_folder:/videos
    env_file:
      - .env
    restart: always
  obs:
    build:
      context: .
      dockerfile: docker/docker_obs/Dockerfile
    shm_size: '256m'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 5901:5901
      - 6901:6901
      - 4455:4455
    depends_on:
      - video_server
    devices:
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - video_folder:/videos
    networks:
      - obs

volumes:
  video_folder:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /media/amor/data/videos
      o: bind

networks:
  obs:
