version: '3'
services:
  tts:
    build:
      context: .
      dockerfile: docker/docker_tts/Dockerfile
    runtime: nvidia
    devices:
      - /dev/nvidia0:/dev/nvidia0
    ports:
      - 8001:8001
    networks:
      - tts
  virtual_streamer:
    build:
      context: .
      dockerfile: docker/docker_worker/Dockerfile
    runtime: nvidia
    depends_on:
      - tts
      - rabbitmq
    devices:
      - /dev/nvidia0:/dev/nvidia0
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMQ_HOST=rabbitmq
      - TTS_HOST=tts
      - OUT_VIDEO_FOLDER=/src/generations
      - S3_BUCKET_URL=virtual-streamer-output
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
    networks:
      - tts
      - rabbit
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - $HOME/.aws/config:/root/.aws/config
    env_file:
      - .env
    restart: always
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbit
  demo:
    build:
      context: .
      dockerfile: docker/docker_base/Dockerfile
    ports:
      - 7861:7861
    depends_on:
      - rabbitmq
    environment:
      - RMQ_HOST=rabbitmq
      - S3_BUCKET_URL=virtual-streamer-output
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
    networks:
      - rabbit
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - $HOME/.aws/config:/root/.aws/config
    env_file:
      - .env


volumes:
  generations:
  prompts:


networks:
  tts:
  rabbit:
