version: '3'
services:
  demo:
    build:
      context: .
      dockerfile: docker/docker_base/Dockerfile
    ports:
      - 7860:7860
    depends_on:
      - rabbitmq
    environment:
      - RMQ_HOST=rabbitmq
      - S3_BUCKET_URL=virtual-streamer-output
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
    networks:
      - rabbit
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - $HOME/.aws/config:/root/.aws/config
    env_file:
      - .env