from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum
import uuid
from datetime import datetime

# --- Enums ---


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    VALIDATING = "VALIDATING"  # Specific status for project validation
    READY_TO_RENDER = "READY_TO_RENDER"  # After validation, before render start
    RENDERING = "RENDERING"  # Overall project render status


class ValidationStatus(str, Enum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID = "INVALID"


# --- Video Server Models ---


class CharacterPresence(BaseModel):
    character_id: str = Field(..., description="Reference to the Character definition")
    start_time: float = Field(
        ...,
        ge=0,
        description="Timestamp (in seconds) relative to the clip start when character appears",
    )
    end_time: float = Field(
        ...,
        gt=0,
        description="Timestamp (in seconds) relative to the clip start when character disappears",
    )


class VideoClipMetadataInput(BaseModel):
    """Metadata provided externally when updating a clip."""

    duration: float = Field(
        ..., gt=0, description="Duration of the video clip in seconds"
    )
    scene_description_text: Optional[str] = Field(
        None, description="Textual description of the scene"
    )
    scene_keywords: Optional[List[str]] = Field(
        None, description="Keywords describing the scene"
    )
    character_presences: List[CharacterPresence] = Field(
        default_factory=list, description="Detected characters and their timings"
    )
    source_show_name: Optional[str] = Field(
        None, description="Name of the original show/source"
    )
    source_episode_name: Optional[str] = Field(
        None, description="Name of the original episode"
    )
    start_time_in_source: Optional[float] = Field(
        None, ge=0, description="Start time within the original large video (seconds)"
    )
    end_time_in_source: Optional[float] = Field(
        None, gt=0, description="End time within the original large video (seconds)"
    )
    # Add any other relevant metadata fields here


class VideoClipBase(BaseModel):
    """Base model for a clip, used for creation request."""

    storage_path: str = Field(
        ..., description="Path/key to the video file (e.g., S3 key)"
    )
    # Metadata might be added later via a separate endpoint
    collection_ids: List[str] = Field(
        default_factory=list,
        description="List of collection IDs this clip belongs to initially",
    )


class VideoClipCreate(VideoClipBase):
    """Data needed to initially create a video clip record."""

    # ID will be generated by the server
    pass


class VideoClip(VideoClipBase):
    """Full VideoClip representation, including generated fields."""

    clip_id: str = Field(..., description="Unique identifier for the video clip")
    metadata: Optional[VideoClipMetadataInput] = Field(
        None, description="Extracted metadata (populated later)"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        orm_mode = True  # If using with an ORM


# --- Character & TTS Models ---


class VoiceSample(BaseModel):
    sample_storage_path: str = Field(
        ..., description="Path/key to the speaker WAV file (e.g., S3 key)"
    )
    transcript: str = Field(..., description="Accurate transcript of the WAV file")


class CharacterBase(BaseModel):
    name: str = Field(..., description="Display name of the character/voice")
    description: Optional[str] = Field(None, description="Optional description")
    video_clip_path: str = Field(
        ..., description="Storage path or URL to the representative video clip"
    )
    voice_samples: List[VoiceSample] = Field(
        ..., min_items=0, description="Samples used to define/clone the voice"
    )
    tts_model_config: Optional[Dict[str, Any]] = None  # Optional: Specific TTS config


class Character(CharacterBase):
    character_id: str = Field(
        ..., description="Unique identifier for the character/voice"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        orm_mode = True


class TTSRequest(BaseModel):
    text: str = Field(..., description="The text to synthesize")
    character_id: str = Field(..., description="The character voice to use")
    # generation_params: Optional[Dict[str, Any]] = None # Optional override TTS params


class TTSResponse(BaseModel):
    """Response after submitting a TTS job."""

    job_id: str = Field(..., description="ID to track the asynchronous generation job")
    status: JobStatus = Field(
        JobStatus.PENDING, description="Initial status of the job"
    )


class TTSJobResult(BaseModel):
    """Result structure for querying TTS job status."""

    job_id: str
    status: JobStatus
    audio_storage_path: Optional[str] = Field(
        None, description="S3 key to the generated audio file (if successful)"
    )
    error_message: Optional[str] = Field(None, description="Details if the job failed")
    duration_seconds: Optional[float] = Field(
        None, description="Duration of the generated audio (if successful)"
    )


# --- LipSync Models ---


class LipSyncRequest(BaseModel):
    video_clip_storage_path: str = Field(
        ..., description="S3 key for the source video clip"
    )
    audio_storage_path: str = Field(
        ..., description="S3 key for the generated audio to sync"
    )
    # Optional hints for face selection if needed:
    # character_id: Optional[str] = None
    # face_bounding_box: Optional[List[int]] = Field(None, description="[x1, y1, x2, y2] coordinates relative to video frame")


class LipSyncResponse(BaseModel):
    """Response after submitting a LipSync job."""

    job_id: str = Field(..., description="ID to track the asynchronous LipSync job")
    status: JobStatus = Field(
        JobStatus.PENDING, description="Initial status of the job"
    )


class LipSyncJobResult(BaseModel):
    """Result structure for querying LipSync job status."""

    job_id: str
    status: JobStatus
    lipsynced_video_storage_path: Optional[str] = Field(
        None, description="S3 key to the resulting video (if successful)"
    )
    error_message: Optional[str] = Field(None, description="Details if the job failed")


# --- Video Builder / Project Models ---


class DialogueEntry(BaseModel):
    entry_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this dialogue line within the scene",
    )
    character_id: str = Field(..., description="ID of the character speaking")
    text: str = Field(..., description="The dialogue text")
    timestamp: float = Field(
        ...,
        ge=0,
        description="Timestamp (in seconds) relative to the start of the *scene* when the dialogue should start",
    )


class VideoOptions(BaseModel):
    subtitles_enabled: bool = Field(
        False, description="Whether to render subtitles for this scene"
    )
    subtitle_style: Optional[Dict[str, Any]] = Field(
        None,
        description='Example: { "font": "Arial", "size": 24, "color": "white", "outline_color": "black", "outline_width": 1 }',
    )
    # Add other options like background music reference, transition effects etc. later


# --- Validation Models ---


class ValidationIssue(BaseModel):
    scene_id: str
    entry_id: Optional[str] = Field(
        None, description="Specific dialogue entry ID if applicable"
    )
    issue_type: str = Field(
        ...,
        description='e.g., "TIMESTAMP_OUT_OF_BOUNDS", "CHARACTER_NOT_PRESENT", "DURATION_MISMATCH", "API_ERROR"',
    )
    message: str = Field(..., description="Human-readable description of the issue")
    severity: str = Field(
        "ERROR", description='e.g., "ERROR", "WARNING"'
    )  # Could be an Enum


class ProjectValidationResult(BaseModel):
    project_id: str
    is_valid: bool = Field(
        ...,
        description="Overall validation status. True if no ERROR severity issues exist.",
    )
    issues: List[ValidationIssue] = Field(default_factory=list)
    validated_at: datetime = Field(default_factory=datetime.utcnow)
